# Generated by Django 4.1.3 on 2022-11-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Moderator', 'Moderator')], default='User', max_length=10),
        ),
    ]
